### PR TITLE
Postfix Operators Fix and Tests

### LINKED ISSUE #77: Postfix Increment and Decrement Operators not respecting order of return and execution
**Postfix Increment Operators**¹ (_lhs++_) and **Postfix Decrement Operators**² (_lhs--_) do not respect the order of operation execution as defined by the ECMA-262v5.1 Standard:
1 - [https://www.ecma-international.org/ecma-262/5.1/#sec-11.3.1](url) 
2 - [https://www.ecma-international.org/ecma-262/5.1/#sec-11.3.2](url)

**E.g.:**
`var i = 1; var a = [false, false]; a[i--] = 1; a;`
returns `a = [1, false]` instead of `a = [false, 1]` which a correct operation should result in.

and conditional expressions that expect such behaviour could result in **infinite loops**. Like:

`var a = [null, null]; for(var i = 0; i < a.length; a[i++] = 0); a;`

### PR DESCRIPTION
**Pull request by Undre4m**
Conditioned the return values for postfix **_Increment_** and **_Decrement_** operators to follow convened order of execution defined on the standard.

Visitor now returns a clone of the original symbol, which is transient and is not appended to the state's _symbols table. Instead the cloned symbol remains alive throughout runtime until it's either discarded or its materiality is **no longer relevant** (The needed values have been used and is not referenced over the subsequent workflow).

Also fixed the tests for this section and added more comprehensive test cases. Fixes #77

### CODE REVIEW

File: src/runtime.js [hunk 1]
```diff
@@ -821,7 +821,6 @@ define([
     };
 
     FirstPass.prototype.visitComment = function (ast) {
-        //TODO Use RegEx
```
Comment (Undre4m) [inline src/runtime.js]: If this was intended to increase efficiency i made some tests and is better of using current indexOf:
https://jsperf.com/regexp-test-vs-string-includes-vs-string-indexof
https://jsperf.com/exist-regexp-test-vs-string-includes-vs-string-indexof

If not i can craft some regex later.

File: src/state.js [hunk 2]
```diff
@@ -28,7 +28,6 @@ define([
     };
 
     State.prototype.addSymbol = function (name, value) {
-        if (value === undefined) value = undefined;
```
Comment (Undre4m) [inline src/state.js]: Removed because purpose = _undefined_. \*Dies after pun causes mass-braincell-suicide\*
